spring:
  datasource:
    url: jdbc:postgresql://v2202501253104311605.luckysrv.de:5432/gpsd_postgres
    username: postgres
    password: parkingautomaterftw
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9000
  tomcat: 
    relaxed-hosts: [.*]

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs