apiVersion: v1
kind: Service
metadata:
  name: gpsd-incident-mgmt
  namespace: gpsd
spec:
  selector:
    app: gpsd-incident-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30090
  type: NodePort

