namespace: gpsd

replicaCount: 1

image:
  repository: gpsd/gpsd-incident-mgmt
  tag: "v0.0.3"
  pullPolicy: Always

service:
  - name: http
    type: ClusterIP
    port: 9000
    targetPort: 9000

env:
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_ROLE: "gpsd-incident-mgmt"

serviceAccount:
  create: true
  name: gpsd-incident-mgmt-sa

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80